config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stores do
    resources :reviews
  end

  namespace :account do
    resources :stores
    resources :reviews
  end

  root "stores#index"

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :store, counter_cache: :reviews_count
  belongs_to :author, class_name: "User", foreign_key: :user_id
  validates :comment,:rating, presence: true

  scope :recent, -> { order("updated_at DESC")}

  def editable_by?(user)
    user && user == author
  end
end

app/models/store.rb
class Store < ActiveRecord::Base
  validates :name, presence: true

  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

  geocoded_by :address
  after_validation :geocode

  has_many :reviews, dependent: :destroy
  belongs_to :owner, class_name: "User", foreign_key: :user_id

  scope :recent, -> { order("updated_at DESC")}

  def editable_by?(user)
    user && user == owner
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :stores
  has_many :reviews
end

app/controllers/account/reviews_controller.rb
class Account::ReviewsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reviews = current_user.reviews.recent
  end
end

app/controllers/account/stores_controller.rb
class Account::StoresController < ApplicationController
  before_action :authenticate_user!
  def index
    @stores = current_user.stores.recent
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
       u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_store, :authenticate_user!

  def new
    @review = @store.reviews.new
  end

  def create
    @review = @store.reviews.build(review_params)
    @review.author = current_user
    if @review.save
      redirect_to store_path(@store), notice: "Successed!"
    else
      render :new
    end
  end

  def edit
    @review = current_user.reviews.find(params[:id])
  end

  def update
    @review = current_user.reviews.find(params[:id])

    if @review.update(review_params)
      redirect_to store_path(@store), notice: "Successed!"
    else
      render :edit
    end
  end

  def destroy
    @review = current_user.reviews.find(params[:id])
    @review.destroy
    redirect_to store_path(@store), alert: "Deleted!"
  end

  private

  def find_store
    @store = Store.find(params[:store_id])
  end

  def review_params
    params.require(:review).permit(:rating,:comment,:store_id)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]

  def index
    @stores = Store.all
    @hash = Gmaps4rails.build_markers(@stores) do |store, marker|
      marker.lat store.latitude
      marker.lng store.longitude
      marker.infowindow render_to_string(partial: "/stores/infowindow",locals: { store: store})
    end
  end

  def new
    @store = Store.new
  end

  def create
    @store = current_user.stores.new(store_params)
    if @store.save
      redirect_to stores_path, notice: "Successed!"
    else
      render :new
    end
  end

  def show
    @store = Store.find(params[:id])
    @reviews = @store.reviews
    @hash = Gmaps4rails.build_markers(@store) do |store, marker|
      marker.lat store.latitude
      marker.lng store.longitude
      marker.infowindow render_to_string(partial: "/stores/infowindow",locals: { store: store})
    end
  end

  def edit
    @store = current_user.stores.find(params[:id])
  end

  def update
    @store = current_user.stores.find(params[:id])
    if @store.update(store_params)
      redirect_to store_path(@store), notice: "Updated!"
    else
      render :edit
    end
  end

  def destroy
    @store = current_user.stores.find(params[:id])
    @store.destroy
    redirect_to stores_path, alert: "Deleted!"
  end

  private

  def store_params
    params.require(:store).permit(:name,:address,:description,:latitude,:longitude)
  end
end

app/helpers/account/reviews_helper.rb
module Account::ReviewsHelper
end

app/helpers/account/stores_helper.rb
module Account::StoresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
    alert_types = { notice: :success, alert: :danger }

    close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true}
    close_button = content_tag(:button, "x", close_button_options)

    alerts= flash.map do |type, message|
      alert_content = close_button + message
      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, class: alert_class)
    end

    alerts.join("\n").html_safe
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def render_review_comment(review)
    simple_format(review.comment)
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright @2016 Gmapstore
  <br>Design by <a href="courses.growthschool.com/courses/rails-101/" target=_new>Xanxus</a>
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="/" class="navbar-brand">GmapStore</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li> <%= link_to "Register", new_user_registration_path %></li>
          <li> <%= link_to("Login", new_user_session_path) %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hi!, <%= current_user.name %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Stores", account_stores_path %></li>
              <li><%= link_to "My Reviews", account_reviews_path %></li>
              <li> <%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li> <%= link_to "Logout", destroy_user_session_path,method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gmapstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//maps.google.com/maps/api/js?key=AIzaSyAYZqOlogA2mDVJlnVVn9SxKofFw7Yegag"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
</head>
<body>

<div class="container-fluid">
  <%= render "common/navbar" %>
  <%= notice_message %>
  <%= yield %>
</div>
<%= render "common/footer" %>

</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for [@store,@review] do |f| %>
    <div class="form-group">
    <div id="star-rating"></div>
    <%= f.input :comment, input_html: { class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submitting...", class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/reviews/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>Edit Reivew</h1>

 <%= render "form", review: @review %>
</div>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score');
    },
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>New Reivew</h1>

  <%= render "form", review: @review %>
</div>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/stores/_form.html.erb
<hr>
  <%= simple_form_for @store do |f| %>
    <div class="form-group">
      <%= f.input :name, input_html: { class: "form-control"} %>
      <%= f.input :address, input_html: { class: "form-control"} %>
      <%= f.hidden_field :latitude, id: "map_lat" %>
      <%= f.hidden_field :longitude,  id: "map_lng" %>
      <%= f.input :description, input_html: { class: "form-control"} %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..."} %>
  <% end %>
<hr>

app/views/stores/_infowindow.html.erb
<h1><%= store.name %></h1>
<p><%= store.address %></p>
<p><%= store.description %></p>

app/views/stores/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>Edit Store</h1>

  <%= render "form", store: @store %>

  <div id="map" style='width: 100%; height: 400px;'></div>
</div>

<script>
  $(function() {
    gmap_form(<%= raw(@store.to_json) %>)
  })
</script>

app/views/stores/index.html.erb
<div class="col-md-12">
  <div class="store">
    <%= link_to "New store", new_store_path, class: "btn btn-primary pull-right" %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Address</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      <% @stores.each do |store| %>
        <tr>
          <td>#</td>
          <td><%= link_to truncate(store.name, length: 15), store_path(store) %></td>
          <td> <%= store.address %> </td>
          <td><%= store.description %></td>
          <td>
              <% if store.editable_by?(current_user) %>
              <%= link_to "Edit", edit_store_path(store), class: "btn btn-sm btn-default" %>
              <%= link_to "Delete", store_path(store), class: "btn btn-sm btn-default",method: :delete, data: { confirm: "Are you sure?"} %>
              <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <hr>
  <div id="map" style='width: 100%; height: 600px;'></div>
</div>

<script>
  $(function() {
    gmap_index(<%= raw @hash.to_json %>);
  });
</script>

app/views/stores/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>New Store</h1>

  <%= render "form",store: @store %>

  <div id="map" style='width: 100%; height: 400px;'></div>
</div>

<!--<div class="container">
  <div id="map" style='width: 100%; height: 800px;'></div>
</div>-->


<script>
  $(function() {
    gmap_form(null)
  })
</script>

app/views/stores/show.html.erb
<div class="col-md-12">
  <div class="store">
    <%= link_to "New Comment", new_store_review_path(@store), class: "btn btn-warning pull-right" %>
    <% if @store.editable_by?(current_user) %>
    <%= link_to "Edit", edit_store_path(@store), class: "btn btn-primary pull-right" %>
    <% end %>
  </div>
  <h2> <%= @store.name %></h2>
  <p> <%= @store.address %></p>
  <p> <%= @store.description %></p>
  <hr>
  <table class="table table-hover">
    <thead>
      <tr>
        <th colspan="2">Reviews</th>
      </tr>
    </thead>
    <tbody>
      <% @reviews.each do |review| %>
      <tr>
        <td><div class="star-rating" data-score= <%= review.rating %>></div></td>
        <td>
        <% if review.editable_by?(current_user) %>
        <%= link_to "Edit", edit_store_review_path(review.store,review), class: "btn btn-default btn-xs" %>
        <%= link_to "Delete", store_review_path(review.store,review), method: :delete, class: "btn btn-default btn-xs", data: { confirm: "Are you sure?"} %>
        <% end %>
        </td>
      </tr>
      <tr>
        <td><%= render_review_comment(review) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <hr>
  <div id="map" style='width: 100%; height: 600px;'></div>
</div>


<script>
  $(function() {
    gmap_index(<%= raw @hash.to_json %>);

    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
        return $(this).attr('data-score');
      }
    });
  })
</script>